version: 2
jobs:
  "build-centos6":
    docker:
      - image: hpcdevops/docker-centos6-rocksbuilder
    working_directory: ~/${CIRCLE_PROJECT_REPONAME}
    steps:
      - checkout
      - run:
          shell: /bin/bash -l
          command: printenv
      - run: |
        printenv |
        grep -v CIRCLE |
        sort

  "build-centos7":
    docker:
      - image: hpcdevops/docker-centos7-rocksbuilder
    working_directory: ~/${CIRCLE_PROJECT_REPONAME}
    steps:
      - checkout
      - run:
          shell: /bin/bash -l
          command: printenv
      - run: |
        printenv |
        grep -v CIRCLE |
        sort

workflows:
  version: 2
  build:
    jobs:
      - "build-centos6"
      - "build-centos7"
