version: 2
jobs:
  "build-centos6":
    docker:
      - image: hpcdevops/docker-centos6-rocksbuilder
        user: rocksbuilder
    steps:
      - checkout
      - run:
          shell: /bin/bash -l
          command: |
            BUILD_DIR=~/$CIRCLE_PROJECT_REPONAME
            cd $BUILD_DIR
            echo "Currently in $(pwd)..."
            echo "CIRCLE Environment is..."
            printenv | grep CIRCLE | sort
            echo "Non-CIRCLE Environment is..."
            printenv | grep -v CIRCLE | sort
            echo "Starting bootstrap and build..."
            ROLL_TO_BUILD=$(awk '/ROLLNAME/ {print $3}' version.mk)
            echo "=-=-=- Build of ${ROLL_TO_BUILD}-roll started at $(date) -=-=-="
            if [ -f ./bootstrap.sh ] ; then
              grep -q yum ./bootstrap.sh && sed -i 's/sudo yum/yum/g;s/yum/sudo yum -y/g;' ./bootstrap.sh
              chmod +x ./bootstrap.sh
              ./bootstrap.sh
              sudo make clean && sudo rm ${PWD}/_arch
            fi
            make default
            for f in $(find . -name "*.iso") ; do
              echo -e "=-=-=- Roll ISO $f Details =-=-=-\n"
              ls -l $f
              echo ""
              isoinfo -R -f -i $f
            done
            cd $BUILD_DIR
            echo "=-=-=- Build of ${ROLL_TO_BUILD}-roll required "$(du -s --block-size=1k ${BUILD_DIR} | awk '{printf "%'\''d KB\n", $1}')" -=-=-="
            cd $BUILD_DIR
            tar -cf - $(find . -name "*.iso") | ( cd $HOME; tar -xvf - )
            cd ~
            ls -ltr
            echo "=-=-=- Build of ${ROLL_TO_BUILD}-roll finished at $(date) -=-=-="

  "build-centos7":
    docker:
      - image: hpcdevops/docker-centos7-rocksbuilder
        user: rocksbuilder
    steps:
      - checkout
      - run:
          shell: /bin/bash -l
          command: |
            BUILD_DIR=~/$CIRCLE_PROJECT_REPONAME
            cd $BUILD_DIR
            echo "Currently in $(pwd)..."
            echo "CIRCLE Environment is..."
            printenv | grep CIRCLE | sort
            echo "Non-CIRCLE Environment is..."
            printenv | grep -v CIRCLE | sort
            echo "Starting bootstrap and build..."
            ROLL_TO_BUILD=$(awk '/ROLLNAME/ {print $3}' version.mk)
            echo "=-=-=- Build of ${ROLL_TO_BUILD}-roll started at $(date) -=-=-="
            if [ -f ./bootstrap.sh ] ; then
              grep -q yum ./bootstrap.sh && sed -i 's/sudo yum/yum/g;s/yum/sudo yum -y/g;' ./bootstrap.sh
              chmod +x ./bootstrap.sh
              ./bootstrap.sh
              sudo make clean && sudo rm ${PWD}/_arch
            fi
            make default
            for f in $(find . -name "*.iso") ; do
              echo -e "=-=-=- Roll ISO $f Details =-=-=-\n"
              ls -l $f
              echo ""
              isoinfo -R -f -i $f
            done
            cd $BUILD_DIR
            echo "=-=-=- Build of ${ROLL_TO_BUILD}-roll required "$(du -s --block-size=1k ${BUILD_DIR} | awk '{printf "%'\''d KB\n", $1}')" -=-=-="
            cd $BUILD_DIR
            tar -cf - $(find . -name "*.iso") | ( cd $HOME; tar -xvf - )
            cd ~
            ls -ltr
            echo "=-=-=- Build of ${ROLL_TO_BUILD}-roll finished at $(date) -=-=-="

workflows:
  version: 2
  build:
    jobs:
      - "build-centos6"
      - "build-centos7"
