version: 2.1
commands:
  bootstrap:
    description: "Run the bootstrap.sh script if it exists."
    parameters:
      rollname:
        description: The name of the roll to build
        type: string
        default: sdsc
    steps:
      - run:
          name: Bootstrap Build Environment
          shell: /bin/bash -l
          command: |
            echo "=-=-=- Build of "<< rollname >>"-roll started at $(date) -=-=-="
            if [ -f ./bootstrap.sh ] ; then
              grep -q yum ./bootstrap.sh && sed -i 's/sudo yum/yum/g;s/yum/sudo yum -y/g;' ./bootstrap.sh
              chmod +x ./bootstrap.sh
              ./bootstrap.sh
              sudo make clean && sudo rm ./_arch
            fi

  make_default:
    description: "Build the roll ISO using the default Makefile target."
    parameters:
      rollname:
        description: the name of the roll to build
        type: string
        default: sdsc-roll
    steps:
      - run:
          name: Build Roll ISO
          shell: /bin/bash -l
          command: |
            ROLLNAME=<< rollname >> make default
  
  verify:
    description: "Check the contents of the produced roll ISO."
    parameters:
      rollname:
        description: the name of the roll to build
        type: string
        default: sdsc-roll
    steps:
      - run:
          name: Verify Roll ISO
          shell: /bin/bash -l
          command: |
            BUILD_DIR=$(pwd)
            for f in $(find . -name "*.iso") ; do
              echo -e "=-=-=- Roll ISO $f Details =-=-=-\n"
              ls -l $f
              echo ""
              isoinfo -R -f -i $f
            done
            cd ~
            echo "=-=-=- Build of ${ROLL_TO_BUILD}-roll required "$(du -s --block-size=1k ${BUILD_DIR} | awk '{printf "%'\''d KB\n", $1}')" -=-=-="
            cd $BUILD_DIR
            tar -cf - $(find . -name "*.iso") | ( cd $HOME; tar -xvf - )
            cd ~
            ls -ltr
            echo "=-=-=- Build of ${ROLL_TO_BUILD}-roll finished at $(date) -=-=-="

jobs:
  "build-centos6":
    docker:
      - image: hpcdevops/docker-centos6-rocksbuilder
        user: rocksbuilder
    steps:
      - checkout
      - bootstrap
      - make_default
      - verify

  "build-centos7":
    docker:
      - image: hpcdevops/docker-centos7-rocksbuilder
        user: rocksbuilder
    steps:
      - checkout
      - bootstrap
      - make_default
      - verify

workflows:
  build:
    jobs:
      - "build-centos6"
      - "build-centos7"
