version: 2
jobs:
  "build-centos6":
    docker:
      - image: hpcdevops/docker-centos6-rocksbuilder
    working_directory: /export/rocks/src/roll
    steps:
      - run: . $HOME/.bash_profile
      - run: mkdir -p /export/rocks/src/roll
      - run: cd /export/rocks/src/roll
      - run: git --version
      - checkout
      - run: git remote -v
      - run: git branch -a
      - run: git status
      - run: git log -n 1

  "build-centos7":
    docker:
      - image: hpcdevops/docker-centos7-rocksbuilder
    working_directory: /export/rocks/src/roll
    steps:
      - run: . $HOME/.bash_profile
      - run: mkdir -p /export/rocks/src/roll
      - run: cd /export/rocks/src/roll
      - run: git --version
      - checkout
      - run: git remote -v
      - run: git branch -a
      - run: git status
      - run: git log -n 1

workflows:
  version: 2
  build:
    jobs:
      - "build-centos6"
      - "build-centos7"
