#!/usr/bin/env bash

set -e
set -x

travis_fold start "after_script"
travis_time_start

case $OS_TYPE in
    centos) .travis/upload_roll ;;
    *) echo "Unknown OS_TYPE $OS_TYPE"; exit 1;;
esac

travis_time_end
travis_fold end "after_script"
