#!/usr/bin/env bash 

set -e
set -x

export -f travis_fold
export -f travis_time_start
export -f travis_time_finish

case $OS_TYPE in
    centos) .travis/clone_deps ;;
    *) echo "Unknown OS_TYPE $OS_TYPE"; exit 1;;
esac
