#!/usr/bin/env bash

set -e
set -x

travis_fold start "before_install"
travis_time_start

if [ -z "$OS_TYPE" ]; then
    # default is ubuntu
    # the first 3 lines enable running travis on personal github repositories
    cd ../..
    if [ ! -d hpcdevops  ]; then mv * hpcdevops; fi
    cd hpcdevops/sdsc-roll
    exit
fi

# run docker as shown at
#  https://djw8605.github.io/2016/05/03/building-centos-packages-on-travisci/

sudo apt-get update
echo 'DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock -s devicemapper"' | \
        sudo tee /etc/default/docker > /dev/null
sudo service docker restart
sleep 5

DOCKER_HUB_URI="hpcdevops/docker-${OS_TYPE}$OS_VERSION-rocksbuilder"
sudo docker pull "$DOCKER_HUB_URI"

travis_time_finish
travis_fold end "before_install"

