#!/usr/bin/env bash 

set -e
set -x

travis_fold start "before_script"
travis_time_start

case $OS_TYPE in
    centos) .travis/clone_deps ;;
    *) echo "Unknown OS_TYPE $OS_TYPE"; exit 1;;
esac

travis_time_finish
travis_fold end "before_script"

