#!/usr/bin/env bash

set -e
set -x

. $HOME/.bash_profile

printenv

ROLL_TO_BUILD=$(awk '/ROLLNAME/ {print $3}' version.mk)

echo "=-=-=- Build of ${ROLL_TO_BUILD}-roll started at $(date) -=-=-="

# Rocks MUST build rolls in a directory at least 3 levels deep from / ...
BUILD_BASE=/tmp/rocksbuilder
BUILD_DIR=${BUILD_BASE}/$(pwd)

mkdir -p ${BUILD_DIR}

tar -cf - . | ( cd ${BUILD_DIR} ; tar -xf - )
cd ${BUILD_DIR}

if [ -f ./bootstrap.sh ] ; then
    grep -q yum ./bootstrap.sh && \
        sed -i 's/sudo yum/yum/g;s/yum/sudo yum -y/g;' ./bootstrap.sh
    chmod +x ./bootstrap.sh
    ./bootstrap.sh
    sudo make clean && \
        sudo rm ${PWD}/_arch
fi

make default

for f in $(find . -name "*.iso") ; do
    echo -e "=-=-=- Roll ISO $f Details =-=-=-\n"
    ls -l $f
    echo ""
    isoinfo -R -f -i $f
done

cd ${BUILD_BASE}

echo "=-=-=- Build of ${ROLL_TO_BUILD}-roll required "\
    $(du -s --block-size=1k ${BUILD_DIR} | awk '{printf "%'\''d KB\n", $1}')" -=-=-="

cd ${BUILD_DIR}

tar -cf - $(find . -name "*.iso") | ( cd $HOME; tar -xvf - )

cd ${HOME}

ls -ltr

echo "=-=-=- Build of ${ROLL_TO_BUILD}-roll finished at $(date) -=-=-="

