#!/usr/bin/env bash

set -e
set -x

DOCKER_HUB_URI="hpcdevops/docker-${OS_TYPE}$OS_VERSION-rocksbuilder"
DOCKER_CONTAINER_NAME="docker-${OS_TYPE}${OS_VERSION}-rocksbuilder"


# $ docker run -it -e "container=docker" -h rocksbuilder -v "$(pwd):/export/rocks/src/roll" -v "/tmp:/tmp" -w "/export/rocks/src/roll" docker-centos7-rocksbuilder bash

if [[ "$OS_TYPE" = "centos" ]] && [[ "$OS_VERSION" = "6" ]]; then
    docker run \
	--cap-drop all \
	--tty \
	--interactive \
	--env "container=docker" \
	--hostname rocksbuilder \
	--name "$DOCKER_CONTAINER_NAME" \
	--volume "$(pwd):/build:ro" \
	--volume "/tmp:/tmp:rw" \
	--user rocksbuiler \
	--workdir "/build"
	"$DOCKER_HUB_URI" /bin/bash -exc "
	    cd /build &&
	    .travis/build $OS_TYPE $OS_VERSION
      "
elif [[ "$OS_TYPE" = "centos" ]] && [[ "$OS_VERSION" = "7" ]]; then
    docker run \
	--cap-drop all \
	--tty \
	--interactive \
	--detach \
	--env "container=docker" \
	--hostname rocksbuilder \
	--name "$DOCKER_CONTAINER_NAME" \
	--volume "$(pwd):/build:ro" \
	--volume "/tmp:/tmp:rw" \
	--user rocksbuiler \
	--workdir "/build"
	"$DOCKER_HUB_URI" /usr/sbin/init
	    docker exec -ti "$DOCKER_CONTAINER_NAME" /bin/bash -exc "
		cd /build &&
		.travis/build $OS_TYPE $OS_VERSION
	    "
else
    docker run \
	--cap-drop all \
	--tty \
	--interactive \
	--env "container=docker" \
	--hostname rocksbuilder \
	--name "$DOCKER_CONTAINER_NAME" \
	--volume "$(pwd):/build:ro" \
	--volume "/tmp:/tmp:rw" \
	--user rocksbuiler \
	--workdir "/build"
	"$DOCKER_HUB_URI" /bin/bash -exc "
	    cd /build &&
	    .travis/build $OS_TYPE $OS_VERSION
	"
fi

docker ps -a
docker stop "$DOCKER_CONTAINER_NAME"
docker rm -v "$DOCKER_CONTAINER_NAME"
