#!/usr/bin/env bash

set -e
set -x

travis_fold start "script"
travis_time_start

case $OS_TYPE in
    centos) .travis/docker_run ;;
    *) echo "Unknown OS_TYPE $OS_TYPE"; exit 1;;
esac

travis_time_end
travis_fold end "script"

